Project ADB_TFE_SERIES_SITE {
  database_type: "MySQL"
  Note: "Travail de fin d'année pour la 1ère année d\'étude à l'IFAPME à Charleroi pour le cours d\'atelier de développement - base."
}

Table Series {
  id int(10) [pk]

  Note: "Cette table ne sert que comme représentation de l'API utilisée. Elle ne n'existe pas car elle est gérée par l'API."
}

Table Users {
  id bigint(20) [pk, increment, note: "unsigned"]
  name varchar(255) [not null, note: "Nom d'utilisateur"]
  first_name varchar(255) [default: null, note: "Prénom de l'utilisateur"]
  last_name varchar(255) [default: null, note: "Nom de famille de l'utilisateur"]
  gender Genders [default: null, note: "Genre de l'utilisateur"]
  birthdate date [note: "Date de naissance au format YYYY-MM-DD"]
  country varchar(50) [note: "Pays d'origine de l'utilisateur"]
  email varchar(255) [not null, unique]
  email_verified_at timestamp [default: null]
  password varchar(255) [not null, note: "hashed password"]
  remember_token varchar(100) [default: null]
  created_at timestamp [not null, default: `CURRENT_TIMESTAMP`]
  updated_at timestamp [default: null]
}

Table Comments {
  id bigint(20) [pk, increment, note: "unsigned"]
  user_id bigint(20) [not null, ref: > Users.id, note: "unsigned"]
  serie_id int(10) [not null, ref: > Series.id]
  comment text [not null]
  created_at timestamp [not null, default: `CURRENT_TIMESTAMP`]
  updated_at timestamp [default: null]
  deleted_at timestamp [default: null]

  indexes {
    (user_id, serie_id) [unique]
  }

}

Table Statistiques {
  id int(10) [pk, increment]
  user_id bigint(20) [not null, ref: > Users.id, note: "unsigned"]
}

// Version Combinée des tables Favorites, Watchlist, Watched et Ratings
// Demander au prof si c'est une bonne idée de faire ça ou pas
Table User_Serie_Interactions {
  id int(10) [pk, increment]
  user_id bigint(20) [not null, ref: > Users.id, note: "unsigned"]
  serie_id int(10) [not null, ref: > Series.id]
  is_favorite boolean [default: false]
  in_watchlist boolean [default: false]
  is_watched boolean [default: false]
  rating int(11) [default: null]
  created_at timestamp [not null, default: `CURRENT_TIMESTAMP`]
  updated_at timestamp [default: null]
  deleted_at timestamp [default: null]

  indexes {
    (user_id, serie_id) [unique]
  }
}

// Table Favorites {
//   id int(10) [pk, increment]
//   user_id bigint(20) [not null, ref: > Users.id, note: "unsigned"]
//   serie_id int(10) [not null, ref: > Series.id]
//   created_at timestamp [not null, default: `CURRENT_TIMESTAMP`]
//   deleted_at timestamp [default: null]

//   indexes {
//     (user_id, serie_id) [unique]
//   }

// }

// Table Watchlist {
//   id int(10) [pk, increment]
//   user_id bigint(20) [not null, ref: > Users.id, note: "unsigned"]
//   serie_id int(10) [not null, ref: > Series.id]
//   created_at timestamp [not null, default: `CURRENT_TIMESTAMP`]
//   deleted_at timestamp [default: null]

//   indexes {
//     (user_id, serie_id) [unique]
//   }

// }

// Table Watched {
//   id int(10) [pk, increment]
//   user_id bigint(20) [not null, ref: > Users.id, note: "unsigned"]
//   serie_id int(10) [not null, ref: > Series.id]
//   created_at timestamp [not null, default: `CURRENT_TIMESTAMP`]
//   deleted_at timestamp [default: null]

//   indexes {
//     (user_id, serie_id) [unique]
//   }

// }

// Table Ratings {
//   id int(10) [pk, increment]
//   user_id bigint(20) [not null, ref: > Users.id, note: "unsigned"]
//   serie_id int(10) [not null, ref: > Series.id]
//   rating int(11) [not null]
//   created_at timestamp [not null, default: `CURRENT_TIMESTAMP`]
//   updated_at timestamp [default: null]
//   deleted_at timestamp [default: null]

//   indexes {
//     (user_id, serie_id) [unique]
//   }

// }

Table Sessions {
  id varchar(255) [pk]
  user_id bigint(20) [default: null, ref: > Users.id, note: "unsigned"]
  ip_address varchar(45) [default: null]
  user_agent text [default: null]
  payload longtext [not null]
  last_activity int(11) [not null]
}

Table Password_Reset_Tokens {
  email varchar(255) [pk]
  token varchar(255) [not null]
  created_at timestamp [default: null]
}

Table Migrations {
  id int(10) [pk, increment, note: "unsigned"]
  migration varchar(255) [not null]
  batch int(11) [not null]
}

Table Jobs {
  id bigint(20) [pk, increment, note: "unsigned"]
  queue varchar(255) [not null]
  payload longtext [not null]
  attempts tinyint(3) [not null, note: "unsigned"]
  reserved_at int(10) [default: null, note: "unsigned"]
  available_at int(10) [not null, note: "unsigned"]
  created_at int(10) [not null, note: "unsigned"]
}

Table Jobs_Batches {
  id varchar(255) [pk]
  name varchar(255) [not null]
  total_jobs int(11) [not null]
  pending_jobs int(11) [not null]
  failed_jobs int(11) [not null]
  failed_jobs_ids longtext [not null]
  options mediumtext [default: null]
  canceled_at int(11) [default: null]
  created_at int(11) [not null]
  finished_at int(11) [default: null]
}

Table Failed_Jobs {
  id bigint(20) [pk, increment, note: "unsigned"]
  uuid varchar(255) [not null, unique]
  connection text [not null]
  queue text [not null]
  payload longtext [not null]
  exception longtext [not null]
  failed_at timestamp [default: `CURRENT_TIMESTAMP`]
}

Table Cache_Locks {
  key varchar(255) [pk]
  owner varchar(255) [not null]
  expiration int(11) [not null]
}

Table Cache {
  key varchar(255) [pk]
  value mediumtext [not null]
  expiration int(11) [not null]
}

Enum Genders {
  "Homme"
  "Femme"
  "Autre"
}
